### ISSUE TITLE
LuaLS/lua-language-server is not loading config.json 

### ISSUE THREAD

**Issue by Penomatikus** [Aoldri/anomaly-definitions#3]
When I follow the readme.md the `LuaLS/lua-language-server` is not recognizing the config file. 

1. Installed `LuaLS/lua-language-server` in VSCode
2. Added a new Profil with an empty settings.json in VSCode
3. Added ```    "Lua.workspace.userThirdParty": [
        "C:\\workspace\\anomaly-definitions"
    ]``` where the path is the root of this project cloned via git
4. Open `D:\Anomaly-1.5.1.2-Modding\gamedata\scripts`

Maybe I missed something, however I thought the LLS is now recognizing at least the `.scripts` files but it doesn't, which is obvious, since the LLS is not prompting me to use the config for "Stalker: Anomaly".

I got it somehow to work with with:
```
{    
    "files.associations": {
        "*.script": "lua"
    },
    "Lua.workspace.userThirdParty": [
        "C:\\workspace\\anomaly-definitions"
    ],
    "Lua.workspace.library": [
      "C:\\workspace\\anomaly-definitions\\library",
      "D:\\Anomaly-1.5.1.2-Modding\\gamedata\\scripts"
    ],
    "Lua.workspace.ignoreSubmodules": false,
    "Lua.diagnostics.disable": [
      "lowercase-global"
    ],
    "Lua.runtime.plugin": "C:\\workspace\\anomaly-definitions\\plugin.lua",
    "Lua.runtime.version": "Lua 5.1",
}
```
As you can see I need to use VSCodes `files.associations`, to have a somehow working state, but this just enables the prompt: "Do You need to configure your work enviroment as 'luafilesystem'?" - which is not "Stalker: Anomaly" and ofcourse ignores your LLS-3rdlib-Config for "files". 

This way I am going down from 30K+ errors to just 2K+ errors, but for example `lua_help.script` alone has 1003 errors. 

Did I missed something?

**Comment by Aoldri** [comment]
Sorry for responding so late, meant to reply much earlier but got sidetracked.

As far as setup goes, I'm not sure why the automatic "Environment Emulation" doesn't work. It did work when I wrote the readme, though not right at this moment as I'm testing it for some reason.
The manual method is as you described, by plugging in the `Lua.workspace.library` and `Lua.runtime.plugin`, which seems to work at least. The `.lua` association with `.script` files is a good point that I overlooked, and I'll update the readme to include it.

As far as errors goes, `lua_help.script` is not a proper `.lua` file, as it serves more as auto-generated documentation for exported stuff from engine so no surprise there. Best off disabling diagnostics for that file at least.
Otherwise, it looks most of the other 'errors' are due to non-standard amounts and types of whitespace used to declare classes, for which I should be able to put out a fix soon.

**Comment by Penomatikus** [comment]
Thank you for looking into my issue! From your answer regarding the `lua_help.script` I added a new rule and removed any false positives by that. Also I disabled some more diagnostics which - I think - producing again false positives. 

In the end I went from 30k+ (initial) to 14k+ (with your repo) to  just 636 warnings. So thank you for your work! 

I've taken the liberty of creating a pull request with my changes which I copied from my workspace to your config.json.
